services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "8080:80"
    volumes:
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www/html
    depends_on:
      - php
      - postgres

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./:/var/www/html

  postgres:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: always

volumes:
  database_data:
