parameters:
    images_dir: '%kernel.project_dir%/public/images'

services:

    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Auth\User\Application\Factory\TokenFactoryInterface:
        class: App\Auth\User\Application\Factory\TokenFactory
        arguments:
            $interval: '%env(TOKEN_TTL)%'
            $uuidFactory: '@uuid.factory'

    App\SharedKernel\Application\Listener\ExceptionListener:
        arguments: [ '%kernel.environment%' ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
