doctrine:
  dbal:
    types:
      user_id: App\Auth\User\Domain\Type\UserIdType
      user_name: App\Auth\User\Domain\Type\UserNameType
      user_email: App\Auth\User\Domain\Type\UserEmailType
      user_status: App\Auth\User\Domain\Type\UserStatusType
